=== rafaelsperoni/webservices2025/xml/books.dtd
<!ELEMENT bookstore (description, book+)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT book (title, price)>
    <!ELEMENT title (#PCDATA)>
    <!ATTLIST title lang (en|pt) "en">
    <!ELEMENT price (#PCDATA)>

=== rafaelsperoni/webservices2025/xml/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "books.dtd" >
<bookstore>
    <description>Lista de livros</description>
    <book>
        <title lang="en">Harry Potter</title>
        <price>29.99</price>
    </book>

    <book>
        <title lang="en">Learning XML</title>
        <price>39.95</price>
    </book>
</bookstore>
